services:
  db:
    image: postgres:15-alpine
    container_name: signal_equipment_db
    environment:
      POSTGRES_DB: signal_equipment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: signal_equipment_backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/signal_equipment
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/app/app
    restart: unless-stopped

volumes:
  postgres_data: